#include <iostream>
/*


each new term in the fibonacci sequence is generated by adding the previous two terms. by starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

by considering the terms in the fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

- o(n) solution
*/
int main(int argc, char** argv)
{
	long fibo1 = 0l, fibo2 = 1l, sum = 0l;
	const long max_fibo = 4000000l;
	while (fibo2 < max_fibo)
	{
		//is even 
		if (fibo2 % 2l == 0l)
		{
			sum += fibo2;
		}
		// generate fibonacci sequence
		long t = fibo1;
		fibo1 = fibo2;
		fibo2 += t;
	}
	std::cout << sum << std::endl;
	return 0;
}