#include <iostream>
/*


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

- O(n) solution
*/
int main(int argc, char** argv)
{
	long fibo1 = 0L, fibo2 = 1L, sum = 0L;
	const long max_fibo = 4000000L;
	while (fibo2 < max_fibo)
	{
		//is even 
		if (fibo2 % 2L == 0L)
		{
			sum += fibo2;
		}
		// generate fibonacci sequence
		long t = fibo1;
		fibo1 = fibo2;
		fibo2 += t;
	}
	std::cout << sum << std::endl;
	return 0;
}